// <auto-generated />
using System;
using BasicRPG.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BasicRPG.Infrastructure.Migrations
{
    [DbContext(typeof(RageDbContext))]
    [Migration("20240119172247_PublicPositionsInSpawns")]
    partial class PublicPositionsInSpawns
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BasicRPG.Domain.Entities.Users.HospitalSpawn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float>("Heading")
                        .HasColumnType("real");

                    b.Property<string>("PositionJson")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("HospitalSpawns");
                });

            modelBuilder.Entity("BasicRPG.Domain.Entities.Users.PlayerSpawn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("PositionJson")
                        .HasColumnType("text");

                    b.Property<int>("SpawnLocation")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("PlayerSpawns");
                });

            modelBuilder.Entity("BasicRPG.Domain.Entities.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CreatedBy")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("Experience")
                        .HasColumnType("integer");

                    b.Property<string>("LastPositionJson")
                        .HasColumnType("text");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<double>("Money")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RegisteredDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
